import { cloudflare } from '@cloudflare/vite-plugin'
import { reactRouter } from '@react-router/dev/vite'
import tailwindcss from '@tailwindcss/vite'
import { defineConfig } from 'vite'
import { iconsSpritesheet } from 'vite-plugin-icons-spritesheet'
import tsconfigPaths from 'vite-tsconfig-paths'
import serverAdapter from 'hono-react-router-adapter/vite'
import path from 'path'
import fs from 'node:fs'

const SRC_TYPES = path.resolve('./public/types.ts')
const DEST_TYPES = path.resolve('./app/components/ui/icons/types.ts')

/** Keeps app/components/ui/icons/types.ts in sync with the file generated by the plugin in public/ */
function syncIconTypes() {
	return {
		name: 'sync-icon-types',
		buildStart() {
			if (fs.existsSync(SRC_TYPES)) {
				fs.copyFileSync(SRC_TYPES, DEST_TYPES)
			}
		},
		handleHotUpdate({ file }: { file: string }) {
			if (file === SRC_TYPES) {
				fs.copyFileSync(SRC_TYPES, DEST_TYPES)
			}
		},
	}
}

export default defineConfig({
	ssr: {
		noExternal: ['react-tweet'],
	},
	server: {
		hmr: {
			overlay: false,
		},
		watch: {
			ignored: ['**/node_modules/**', '**/.wrangler/**'],
		},
		fs: {
			allow: ['..'],
		},
	},
	build: {
		assetsDir: 'assets',
	},
	plugins: [
		reactRouter(),
		{
			name: 'css-hmr-fix',
			handleHotUpdate({ file, server }) {
				if (file.endsWith('.css')) {
					server.ws.send({
						type: 'custom',
						event: 'css-update',
						data: { file },
					})
					return []
				}
			},
		},
		tailwindcss(),
		cloudflare({
			persistState: false,
			viteEnvironment: { name: 'ssr' },
		}),
		tsconfigPaths(),
		// Genera sprite en public/ y types.ts también en public/ (luego syncIconTypes lo copia)
		iconsSpritesheet({
			inputDir: './other/icons',
			outputDir: './public',
			fileName: 'sprite.svg',
			withTypes: true,
			formatter: 'biome',
			iconNameTransformer: (name) => name,
		}),
		// Copia automáticamente public/types.ts → app/components/ui/icons/types.ts
		syncIconTypes(),
		serverAdapter({
			entry: 'server/index.ts',
			exclude: [
				// defaults de @hono/vite-dev-server
				/.*\.css$/,
				/.*\.ts$/,
				/.*\.tsx$/,
				/^\/@.+$/,
				/\?t\=\d+$/,
				/^\/favicon\.ico$/,
				/^\/static\/.+/,
				/^\/node_modules\/.*/,
				'/assets/**',
				'/src/app/**',
				/\?(?:inline|url|no-inline|raw|import(?:&(?:inline|url|no-inline|raw)?)?)$/,
				/\?t=\d+&url$/,
			],
		}),
	],
	resolve: {
		alias: {
			'@': path.resolve(__dirname, './app'),
		},
	},
})

